version: '3'
volumes:
  datadb:
services:
  db:
    image: postgres:alpine
    environment:
      POSTGRES_USER: "postgres"
      POSTGRES_DB: "error-manager"
      POSTGRES_PASSWORD: "postgres"
    ports:
      - "15432:5432"
    volumes:
      # Volume dos dados do postgres
      - datadb:/var/lib/postgresql/data