version: 2.1

orbs:
  maven: circleci/maven@0.0.12  
  heroku: circleci/heroku@1.0.1

workflows:
  maven_test:
    jobs:
      - maven/test 
  heroku_deploy:
    jobs:      
      - heroku/deploy-via-git