version: 2.1

orbs:
  maven: circleci/maven@0.0.12

workflows:
  maven_test:
    jobs:
      - maven/test # checkout, build, test, and upload test results
  heroku_deploy:
    jobs:      
      - heroku/deploy-via-git: # Use the pre-configured job, deploy-via-git
          requires:
            - maven_test
          filters:
            branches:
              only: sequential-branch-filter